wandb_version: 1

output_dir:
  desc: null
  value: /home/ndhuynh/github/HieVQA/results
device:
  desc: null
  value: cuda
world_size:
  desc: null
  value: 2
dist_url:
  desc: null
  value: env://
distributed:
  desc: null
  value: true
bs:
  desc: null
  value: 32
bs_test:
  desc: null
  value: 32
data_path:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa
model:
  desc: null
  value: VQA-HieVQA
dataset:
  desc: null
  value: simpsonsvqa
note:
  desc: null
  value: 9types-debug
version:
  desc: null
  value: ''
task:
  desc: null
  value: hievqa
debug:
  desc: null
  value: false
wandb:
  desc: null
  value: true
wandb_dir:
  desc: null
  value: null
checkpoint:
  desc: null
  value: ''
save_model:
  desc: null
  value: true
model_config:
  desc: null
  value:
    image_feature_output: 1024
    img_size: 224
    text_enc: rnn
    word_embedding: 300
    rnn_hidden_size: 512
    ques_feature_output: 1024
    number_layer: 2
    bidirectional: false
    image_channel_type: normi
    use_glove: true
data_config:
  desc: null
  value:
    train_ann:
    - v1_Annotation_Train_simpsons_vqa.json
    val_ann:
    - v1_Annotation_Val_simpsons_vqa.json
    test_ann:
    - v1_Annotation_Test_Private_110496_simpsons_vqa.json
    train_que:
    - v1_Question_Train_simpsons_vqa.json
    val_que:
    - v1_Question_Val_simpsons_vqa.json
    test_que:
    - v1_Question_Test_Private_110496_simpsons_vqa.json
    train_image:
    - train_images
    val_image:
    - val_images
    test_image:
    - test_images
    stat_ques_list:
    - v1_Question_Train_simpsons_vqa.json
    - v1_Question_Val_simpsons_vqa.json
    stat_answer_list:
    - v1_Annotation_Train_simpsons_vqa.json
    - v1_Annotation_Val_simpsons_vqa.json
    annotation_dict: dataset/annotations_type_simpsonsvqa.json
    question_dict: dataset/questions_simpsonsvqa.pkl
    top_answers: 1000
    super_type: dataset/super_answer_type_simpsons.json
num_dec_layers:
  desc: null
  value: 6
batch_size_train:
  desc: null
  value: 16
batch_size_test:
  desc: null
  value: 16
max_tokens:
  desc: null
  value: 20
k_test:
  desc: null
  value: 128
max_ques_len:
  desc: null
  value: 20
optimizer:
  desc: null
  value:
    opt: adamW
    lr: 10e-4
    weight_decay: 0.01
    lr_mult: 2
schedular:
  desc: null
  value:
    sched: linear
    lr: 10e-5
    epochs: 100
    num_warmup_steps: 1
start_eval:
  desc: null
  value: 0
print_freq:
  desc: null
  value: 50
delta:
  desc: null
  value: 0.7
rank:
  desc: null
  value: 1
gpu:
  desc: null
  value: 1
dist_backend:
  desc: null
  value: nccl
_wandb:
  desc: null
  value:
    code_path: code/running.py
    python_version: 3.9.16
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704704635.217208
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 33
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.9.16
      5: 0.15.5
      6: 4.36.2
      8:
      - 5
